# Form implementation generated from reading ui file '.\wb.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(310, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\favicon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.label_main_menu = QtWidgets.QLabel(Form)
        self.label_main_menu.setEnabled(True)
        self.label_main_menu.setGeometry(QtCore.QRect(10, 10, 290, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_main_menu.setFont(font)
        self.label_main_menu.setObjectName("label_main_menu")
        self.cb_main_menu = QtWidgets.QComboBox(Form)
        self.cb_main_menu.setGeometry(QtCore.QRect(10, 30, 290, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.cb_main_menu.setFont(font)
        self.cb_main_menu.setObjectName("cb_main_menu")
        self.label_category = QtWidgets.QLabel(Form)
        self.label_category.setEnabled(True)
        self.label_category.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_category.setFont(font)
        self.label_category.setObjectName("label_category")
        self.cb_category = QtWidgets.QComboBox(Form)
        self.cb_category.setGeometry(QtCore.QRect(10, 80, 290, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.cb_category.setFont(font)
        self.cb_category.setObjectName("cb_category")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Wildberries"))
        self.label_main_menu.setText(_translate("Form", "select the main menu section:"))
        self.label_category.setText(_translate("Form", "select product category:"))
